language: java
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

addons:
  apt:
    sources:
    packages:
      # Getting compile errors on javac 1.8.0_31-b13
      - nodejs-legacy
      - npm

install: "mvn clean install"
